name: ci

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CI: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: load cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}

      - name: install dependencies
        run: pnpm install

      - name: build packs
        run: pnpm build

      - name: run e2e test on chrome
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_SERVER_PORT: 7000
          CYPRESS_PORT: 8000
        with:
          install: false
          working-directory: e2e
          start: pnpm exec vite preview --port 7000 --host
          wait-on: 'http://localhost:7000'
          browser: chrome

      - name: run e2e test on firefox
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_SERVER_PORT: 7001
          CYPRESS_PORT: 8000
        with:
          install: false
          working-directory: e2e
          start: pnpm exec vite preview --port 7001 --host
          wait-on: 'http://localhost:7001'
          browser: firefox

      - name: create versions or publish to npm registry
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changeset): release prosemirror-adapter'
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
