name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest-esr

      - name: Run e2e test on chrome
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_SERVER_PORT: 7000
          CYPRESS_PORT: 8000
        with:
          install: false
          working-directory: e2e
          start: pnpm exec vite preview --port 7000 --host
          wait-on: "http://localhost:7000"
          browser: chrome

      - name: Run e2e test on firefox
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_SERVER_PORT: 7001
          CYPRESS_PORT: 8000
        with:
          install: false
          working-directory: e2e
          start: pnpm exec vite preview --port 7001 --host
          wait-on: "http://localhost:7001"
          browser: firefox
