name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

      - name: Install browsers
        run: pnpm run test:install

      - name: Run e2e tests
        run: pnpm run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 7

  preview-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup


      - name: Publish snapshot packages
        if: ${{ github.event_name == 'pull_request' }}
        run: >
          ./node_modules/.bin/pkg-pr-new publish --pnpm './packages/*'
