name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Create versions or publish to npm registry
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changeset): release prosemirror-adapter'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Export screenshots (on failure only)
        uses: actions/upload-artifact@v4.4.3
        if: ${{ failure() }}
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots
          retention-days: 7

      - name: Export screen recordings (on failure only)
        uses: actions/upload-artifact@v4.4.3
        if: ${{ failure() }}
        with:
          name: cypress-videos
          path: e2e/cypress/videos
          retention-days: 7
